### ISSUE TITLE
previewer/translator Page not found

### ISSUE THREAD

**Issue by lief-erickson** [jekyll-one/jekyll-one#1]
https://jekyll.one/pages/public/previewer/translator/

**Comment by jekyll-one** [comment]
Hello Lief,

thanks for giving J1 Template a try. Sorry for being late with my answer.

You've raised several questions; two of them are placed on a (technical)
sister repo at https://github.com/jekyll-one/j1-template-starter.

@jekyll-one/jekyll-one/1

Dead link.

Sorry for the dead link. I removed the reviewer page for translations because most translators are commercial and offer only paid services. The primary translator for J1 is Google Translator GTR (Base). The base service can be used for free and is fully integrated with the template. Testing the service is simple: run GTR (for the whole web) by clicking the GTR icon in the quick links bar (top left in the menubar).

2. @jekyll-one/j1-template-starter/1

Where is the best place to ask usage and clarification questions?

The best place is (here) at jekyll-one/jekyll-one. I'll remove the issues
section at the repo jekyll-one/j1-template-starter.

The repo @jekyll-one/j1-template-starter is used ONLY for technical reasons. Some sites present my example webs but use HTML iFrames to display. To make using  HTML iFrames possible, some cookie settings are to be adjusted. These settings allow so-called 'cross-site' requests and are NOT recommended for public websites on the Internet. In other words: you need to know what you're doing if 'cross-site' requests are allowed for a site. The default cookie settings for J1-based webs reject 'cross-site' requests for security reasons.

The issues section (support) is mainly used to raise attention on errors or other misbehavior for code fixing. Usage questions (consulting) can only be answered very limitedly, or they are rejected. Questions addressing the usage of J1 as a tool are often too open or focussing on technical areas like the usage of Cookies, Webdesign or the generator Jekyll. It would be best if you asked questions for consulting on forum websites like http://stackoverflow.com/questions/tagged/jekyll or http://jekyll.tips/.


Do you accept pull requests?

Yes, sure. I'm open for any suggestion or for help on fixing issues.


Your code snippet from _data/layouts/page.yml.

With the latest version of the J1 GEM  2022.4.4, I changed the comments of all layout-related files. Some comments in older versions were confusing, outdated, or are not valid anymore.

3. @jekyll-one/j1-template-starter/2

Overload which file how?

In general, the J1 Template should be configured, not modified. Code changes (for the GEM version) of the code base are not recommended. This is different in comparison to other templates available for Jekyll. Most other templates are scaffolds/skeletons that are needed to be modified for individual usage. If you plan to modify the GEM version of J1 (runtime version), add/create your files (e.g., a new type of layout) rather than changing the existing code base. This ensures that your website will continue to work for newer versions of the J1 Template GEM.

From your questions, I assume you intend to modify the code. As mentioned, create and add your code to not conflict with the existing code base. The layout system used by Jekyll is not easy to understand. 1 put much more complexity on top to make J1 fully configurable. Work in this area requires a good knowledge of programming techniques for HTML, CSS, Javascript, Liquid, Jekyll, and Ruby, as well as using XML and Yaml. Again, consider what you're doing if you modify the Template.

If your term of overloading means adding and injecting your (custom) code for layouts, it is quite simple to manage. Please check the layout config home.yml of the latest version v2022.4.4 of the GEM. The(new) comments explain where to place custom code and how to inject it.

Finally, a better solution to customize J1 may be creating your template GEM. The J1 development system (development version) is available at Github: https://github.com/jekyll-one-org/j1-template.
